creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - age1vn2ez96nfafhg8atmxq4mq794epk68xudysnwu90rdllj2jceamq5gm53r # primary (personal)
          - age1hk0z5pea89kgnnldk9dx962ddlj59dmr0z6s6fjst4khgz6vpplqyt2089 # vmnixos
          - age1nxx3vtw04s0ur97uw7jhgpys8jtu0dqwkpflzv9ek485fjcl3epqpl6fsx # ncc1701e
