# Home-manager config for brpol.
# This directory is the entry point; split into sub-files and import them here
# as the config grows (e.g. ./shell.nix, ./git.nix, ./neovim.nix).
{
  pkgs,
  lib,
  stateVersion,
  rcfilesSrc ? null, # Nix store path of working tree; injected by mkHost
  rcfilesRev ? null, # git SHA of the baked-in revision; null when dirty or standalone HM
  ...
}: let
  seed-rcfiles-from-nix-store = import ./scripts/seed-rcfiles-from-nix-store.nix {inherit pkgs;};
  rcfiles = import ../../../lib/rcfiles.nix;

  # Desktop notification at graphical login if the personal age key is absent.
  ageKeyMissingNotify = pkgs.makeDesktopItem {
    name = "age-key-missing-notify";
    desktopName = "Age Key Missing Notify";
    exec = pkgs.writeShellScript "age-key-missing-notify" ''
      [ -f "$HOME/.config/sops/age/keys.txt" ] && exit 0
      ${pkgs.noti}/bin/noti -t "Age Key Missing" \
        -m "Run ensure-age-key to fetch from Bitwarden"
    '';
    # Cinnamon/GNOME read this to decide whether to run the entry at login.
    extraConfig."X-GNOME-Autostart-enabled" = "true";
  };
in {
  imports = [
    ./scripts
    ./secrets.nix
    ./rust.nix
    ./git.nix
    ./jj.nix
    ./zsh
    ./tmux.nix
    ./timewarrior.nix
    ./vscode.nix
    ./nvim.nix
  ];

  home.username = "brpol";
  home.homeDirectory =
    if pkgs.stdenv.isDarwin
    then "/Users/brpol"
    else "/home/brpol";

  # Passed in from mkHost via home-manager.extraSpecialArgs — single source of truth.
  home.stateVersion = stateVersion;

  # Desktop notification at graphical login if age key is absent.
  # XDG autostart is used instead of a systemd user service because Cinnamon+LightDM
  # does not reliably activate graphical-session.target for systemd user services.
  # The .desktop file is generated by pkgs.makeDesktopItem (see ageKeyMissingNotify)
  # rather than hand-written, and linked into ~/.config/autostart by xdg.autostart.
  xdg.autostart = {
    enable = true;
    entries = ["${ageKeyMissingNotify}/share/applications/age-key-missing-notify.desktop"];
  };

  # Seed ~/rcfiles-nix on a fresh machine.
  # The working tree is baked into the Nix closure via inputs.self (rcfilesSrc), so no
  # network access is needed for the files themselves. A git fetch is attempted afterward
  # to populate full history; it is tolerated if the machine is offline at first boot.
  # brpol-setup switches the remote from HTTPS to SSH after credentials are available.
  home.activation.cloneRcfiles = lib.hm.dag.entryAfter ["writeBoundary"] ''
    _flake_path=''${NH_FLAKE:-$HOME/${rcfiles.checkoutDir}}

    # Validate the target before doing anything destructive (rm -rf below).
    case "$_flake_path" in
      /*) ;;
      *)
        echo "cloneRcfiles: refusing to seed non-absolute path: $_flake_path" >&2
        exit 1
        ;;
    esac

    if [ ! -d "$_flake_path/.git" ]; then
      ${
      if rcfilesSrc != null
      then ''
        ${lib.getExe seed-rcfiles-from-nix-store} "$_flake_path" "${rcfilesSrc}"
        if ${pkgs.git}/bin/git -C "$_flake_path" fetch origin 2>/dev/null; then
          ${
          if rcfilesRev != null
          then ''            ${pkgs.git}/bin/git -C "$_flake_path" reset --hard "${rcfilesRev}" 2>/dev/null \
                              || ${pkgs.git}/bin/git -C "$_flake_path" reset --hard origin/HEAD 2>/dev/null \
                              || true''
          else ''${pkgs.git}/bin/git -C "$_flake_path" reset --hard origin/HEAD 2>/dev/null || true''
        }
        else
          # Offline first activation: the seed left an initialized-but-historyless
          # .git (git init + remote add, no fetched commits). Drop it — keeping the
          # seeded working files — so a later online activation re-enters this block
          # and retries the fetch instead of seeing .git and skipping forever.
          ${pkgs.coreutils}/bin/rm -rf "$_flake_path/.git"
        fi
      ''
      else ''
        ${pkgs.git}/bin/git clone \
          ${lib.escapeShellArg rcfiles.repoUrl} \
          "$_flake_path"
      ''
    }
    fi
    unset _flake_path
  '';

  # Lets home-manager manage itself; required when using the NixOS module.
  programs.home-manager.enable = true;
}
