# Host config for vmnixos — the local NixOS VM.
# Only put things here that are genuinely specific to this machine:
# bootloader, network identity, timezone, hardware.
# Shared settings live in modules/common.nix; GUI stack in modules/desktop.nix.
{
  stateVersion,
  hostname,
  ...
}: {
  imports = [
    ./hardware-configuration.nix # generated by nixos-generate-config; do not hand-edit
  ];

  boot.loader.grub = {
    enable = true;
    device = "/dev/sda";
    useOSProber = true;
    theme = ../../grub-themes/fallout;
  };

  networking.hostName = hostname;
  networking.networkmanager.enable = true;

  time.timeZone = "Asia/Tokyo";

  system.stateVersion = stateVersion;
}
