# Host config for vmnixos — the local NixOS VM.
# Only put things here that are genuinely specific to this machine:
# bootloader, network identity, timezone, hardware.
# Shared settings live in modules/common.nix; GUI stack in modules/desktop.nix.
{stateVersion, ...}: {
  imports = [
    ./hardware-configuration.nix # generated by nixos-generate-config; do not hand-edit
  ];

  boot.loader.grub.device = "/dev/sda";

  networking.hostName = "vmnixos";
  networking.networkmanager.enable = true;

  time.timeZone = "Asia/Tokyo";

  # Changing stateVersion after the initial install can break stateful services.
  # Only bump it when NixOS release notes explicitly say to. Set in flake.nix mkHost call.
  # VM — long sudo timeout so it doesn't keep asking mid-session.
  security.sudo.extraConfig = ''
    Defaults timestamp_timeout=120
  '';

  system.stateVersion = stateVersion;
}
