#!/bin/sh
set -eu

CONFIG_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SOURCES_FILE="$CONFIG_DIR/plugin-sources.txt"
FLAG_FILE="$CONFIG_DIR/.plugins_bootstrapped"
LOCK_DIR="$CONFIG_DIR/.plugins_bootstrap.lock"
CHECK_CHANGES=false

if [ "${1:-}" = "--if-changed" ]; then
  CHECK_CHANGES=true
elif [ "$#" -ne 0 ]; then
  echo "usage: $0 [--if-changed]" >&2
  exit 2
fi

if ! mkdir "$LOCK_DIR" 2>/dev/null; then
  # Another startup hook is already handling this plugin set.
  exit 0
fi

FINGERPRINT_FILE=$(mktemp "${TMPDIR:-/tmp}/herdr-plugin-fingerprint.XXXXXX")
FLAG_TMP="$FLAG_FILE.tmp.$$"
cleanup() {
  rm -f "$FINGERPRINT_FILE" "$FLAG_TMP"
  rmdir "$LOCK_DIR" 2>/dev/null || true
}
trap cleanup EXIT HUP INT TERM

# Build a machine-independent fingerprint from the declarations and every local
# plugin file. plugins.json is generated by Herdr and intentionally not used.
sed '/^[[:space:]]*#/d; /^[[:space:]]*$/d' "$SOURCES_FILE" > "$FINGERPRINT_FILE"
cksum "$CONFIG_DIR/reinstall_plugins.sh" |
  sed "s|$CONFIG_DIR/||" >> "$FINGERPRINT_FILE"
while read -r kind plugin_id relative_path extra; do
  [ -n "${kind:-}" ] || continue
  case "$kind" in
    \#*) continue ;;
    github)
      [ -n "${plugin_id:-}" ] && [ -z "${relative_path:-}" ] && [ -z "${extra:-}" ] || {
        echo "invalid GitHub plugin declaration: $kind ${plugin_id:-} ${relative_path:-} ${extra:-}" >&2
        exit 2
      }
      ;;
    local)
      [ -n "${plugin_id:-}" ] && [ -n "${relative_path:-}" ] && [ -z "${extra:-}" ] || {
        echo "invalid local plugin declaration: $kind ${plugin_id:-} ${relative_path:-} ${extra:-}" >&2
        exit 2
      }
      plugin_dir="$CONFIG_DIR/$relative_path"
      [ -f "$plugin_dir/herdr-plugin.toml" ] || {
        echo "missing local plugin manifest: $plugin_dir/herdr-plugin.toml" >&2
        exit 1
      }
      find "$plugin_dir" -type f -exec cksum {} \; |
        sed "s|$CONFIG_DIR/||" |
        sort >> "$FINGERPRINT_FILE"
      ;;
    *)
      echo "unknown plugin source kind: $kind" >&2
      exit 2
      ;;
  esac
done < "$SOURCES_FILE"

if command -v sha256sum >/dev/null 2>&1; then
  SOURCES_HASH=$(sha256sum "$FINGERPRINT_FILE" | awk '{print $1}')
elif command -v shasum >/dev/null 2>&1; then
  SOURCES_HASH=$(shasum -a 256 "$FINGERPRINT_FILE" | awk '{print $1}')
else
  # cksum is specified by POSIX and is sufficient as a change detector.
  SOURCES_HASH=$(cksum "$FINGERPRINT_FILE" | awk '{print $1 ":" $2}')
fi

if [ "$CHECK_CHANGES" = true ] &&
   [ -f "$FLAG_FILE" ] &&
   [ "$(cat "$FLAG_FILE")" = "$SOURCES_HASH" ]; then
  exit 0
fi

# Unlink every declared local plugin before replacing its registration. This
# clears absolute paths written on another machine and refreshes changed hooks.
while read -r kind plugin_id relative_path extra; do
  [ "$kind" = local ] || continue
  "${HERDR_BIN_PATH:-herdr}" plugin unlink "$plugin_id" >/dev/null 2>&1 || true
done < "$SOURCES_FILE"

while read -r kind plugin_id relative_path extra; do
  [ "$kind" = local ] || continue
  "${HERDR_BIN_PATH:-herdr}" plugin link "$CONFIG_DIR/$relative_path" --enabled
done < "$SOURCES_FILE"

while read -r kind repository relative_path extra; do
  [ "$kind" = github ] || continue
  "${HERDR_BIN_PATH:-herdr}" plugin install "$repository" --yes
done < "$SOURCES_FILE"

umask 077
printf '%s\n' "$SOURCES_HASH" > "$FLAG_TMP"
mv "$FLAG_TMP" "$FLAG_FILE"
