# Host config for ncc1701e — my main home pc as of June 2026
# Only put things here that are genuinely specific to this machine:
# bootloader, network identity, timezone, hardware.
# Shared settings live in modules/common.nix; GUI stack in modules/desktop.nix.
{
  stateVersion,
  hostname,
  ...
}: {
  imports = [
    ./hardware-configuration.nix # generated by nixos-generate-config; do not hand-edit
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = hostname;
  networking.networkmanager.enable = true;

  time.timeZone = "Asia/Tokyo";

  system.stateVersion = stateVersion;
}
